'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { createApp } = require('../src/app.cjs');
const { loadConfig } = require('../src/config.cjs');

const config = loadConfig({ NODE_ENV:'test' }); const headers = { host:config.allowedHost };
const ZONE_A='20000000-0000-4000-8000-0000000000a1'; const ZONE_B='20000000-0000-4000-8000-0000000000b2';
function fakeDatabase(options={}){const calls=[];return{calls,async query(text){calls.push(String(text));if(String(text).includes('community_stats'))return{rows:[options.suppressed?{published_count:null,pending_count:null,rejected_count:null,avg_resolution_hours:null,network_version:'osm-1',pilot_empty:false,privacy_suppressed:true}:{published_count:'6',pending_count:'2',rejected_count:'2',avg_resolution_hours:'12.5',network_version:'osm-1',pilot_empty:false,privacy_suppressed:false}]};if(String(text).includes('zone_leaderboard'))return{rows:[{id:ZONE_A,slug:'zona-a',name:'Zona A',sort_order:10,is_approximate:true,bbox:[-6.01,37.37,-6,37.4],published_count:'6',pending_count:'2',last_activity:'2026-09-29T10:00:00Z',privacy_suppressed:false},{id:ZONE_B,slug:'zona-b',name:'Zona B',sort_order:20,is_approximate:true,bbox:[-6,37.38,-5.99,37.4],published_count:null,pending_count:null,last_activity:null,privacy_suppressed:true}]};if(String(text).includes('activity_summary'))return{rows:[{window_days:7,published_count:null,submitted_count:null,resolved_count:null,privacy_suppressed:true},{window_days:30,published_count:'6',submitted_count:'8',resolved_count:'4',privacy_suppressed:false}]};throw new Error('unexpected query');}};}
async function withApp(options,run){const app=createApp({config,logger:false,...options});try{await run(app);}finally{await app.close();}}

test('estadísticas usan tasa de publicación y ETag estable',async()=>{const database=fakeDatabase();await withApp({database},async app=>{const first=await app.inject({method:'GET',url:'/api/v1/stats',headers});assert.equal(first.statusCode,200);const body=first.json();assert.equal(body.published,6);assert.equal(body.publicationRate,0.75);assert.equal(body.verificationRate,undefined);assert.equal(body.avgResolutionHours,12.5);assert.equal(body.privacySuppressed,false);assert.match(first.headers.etag,/^"[0-9a-f]{64}"$/);const second=await app.inject({method:'GET',url:'/api/v1/stats',headers:{...headers,'if-none-match':first.headers.etag}});assert.equal(second.statusCode,304);assert.equal(database.calls.filter(value=>value.includes('community_stats')).length,1);});});

test('estadísticas protegen grupos de menos de cinco participantes',async()=>{await withApp({database:fakeDatabase({suppressed:true})},async app=>{const body=(await app.inject({method:'GET',url:'/api/v1/stats',headers})).json();assert.equal(body.published,null);assert.equal(body.pending,null);assert.equal(body.publicationRate,null);assert.equal(body.privacySuppressed,true);assert.match(body.notice,/cinco participantes/);});});

test('zonas paginan, exponen solo bbox y mantienen supresión',async()=>{await withApp({database:fakeDatabase()},async app=>{const first=(await app.inject({method:'GET',url:'/api/v1/zones/leaderboard?limit=1',headers})).json();assert.equal(first.data[0].slug,'zona-a');assert.ok(first.page.nextCursor);assert.equal(JSON.stringify(first).includes('boundary'),false);const second=(await app.inject({method:'GET',url:`/api/v1/zones/leaderboard?limit=1&cursor=${first.page.nextCursor}`,headers})).json();assert.equal(second.data[0].privacySuppressed,true);assert.equal(second.data[0].published,null);assert.equal(second.page.nextCursor,null);});});

test('cursor inválido falla antes de consultar datos',async()=>{const database=fakeDatabase();await withApp({database},async app=>{const response=await app.inject({method:'GET',url:'/api/v1/zones/leaderboard?cursor=manipulado',headers});assert.equal(response.statusCode,422);assert.equal(response.json().code,'INVALID_CURSOR');assert.equal(database.calls.length,0);});});

test('metodología pública distingue lo implementado de lo propuesto',async()=>{await withApp({},async app=>{const response=await app.inject({method:'GET',url:'/api/v1/methodology',headers});assert.equal(response.statusCode,200);const body=response.json();assert.equal(body.status,'implemented');assert.equal(body.privacy.minGroupSize,5);assert.match(body.scoring.proposed.note,/no implementada/);assert.match(body.safety,/Ruta orientativa/);});});

test('actividad de 7 y 30 días conserva privacidad por ventana',async()=>{await withApp({database:fakeDatabase()},async app=>{const body=(await app.inject({method:'GET',url:'/api/v1/activity/summary',headers})).json();assert.deepEqual(body.windows.map(item=>item.days),[7,30]);assert.equal(body.windows[0].published,null);assert.equal(body.windows[0].privacySuppressed,true);assert.equal(body.windows[1].published,6);assert.equal(body.pilotEmpty,false);});});

test('sin base las métricas fallan de forma segura',async()=>{await withApp({},async app=>{for(const url of ['/api/v1/stats','/api/v1/zones/leaderboard','/api/v1/activity/summary']){const response=await app.inject({method:'GET',url,headers});assert.equal(response.statusCode,503);assert.equal(response.json().code,'DATABASE_UNAVAILABLE');assert.equal(response.body.includes('postgres'),false);}});});

test('robots excluye autenticación y sitemap no indexa verificación',async()=>{await withApp({},async app=>{const sitemap=await app.inject({method:'GET',url:'/sitemap.xml',headers});assert.equal(sitemap.statusCode,200);assert.equal(sitemap.body.includes('/auth/verify'),false);const robots=await app.inject({method:'GET',url:'/robots.txt',headers});assert.match(robots.body,/Disallow: \/auth\/verify/);assert.match(robots.body,/Disallow: \/api\/v1\/auth\//);});});
