'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');
test('Render queda gratis, con health y secretos fuera del repositorio',()=>{const yaml=fs.readFileSync(path.join(root,'render.yaml'),'utf8');assert.match(yaml,/plan: free/);assert.match(yaml,/healthCheckPath: \/api\/v1\/health/);assert.match(yaml,/HOST[\s\S]*0\.0\.0\.0/);for(const name of ['DATABASE_URL','SESSION_SECRET','CSRF_SECRET','IDENTITY_ENCRYPTION_KEY','IP_HASH_SECRET','BREVO_API_KEY'])assert.match(yaml,new RegExp(`key: ${name}\\s+sync: false`));assert.doesNotMatch(yaml,/postgresql:\/\/|xkeysib-/);});
test('Render queda ligado a main protegido y despliega cada commit fusionado',()=>{const yaml=fs.readFileSync(path.join(root,'render.yaml'),'utf8');assert.match(yaml,/branch: main/);assert.match(yaml,/autoDeployTrigger: commit/);assert.match(yaml,/npm ci --omit=dev --ignore-scripts/);});
test('CI usa Node 24, acciones Node 24, runner fijado, npm ci, concurrencia y auditoría alta',()=>{const ci=fs.readFileSync(path.join(root,'.github','workflows','ci.yml'),'utf8');assert.match(ci,/workflow_dispatch:/);assert.match(ci,/cancel-in-progress: true/);assert.match(ci,/runs-on: ubuntu-24\.04/);assert.match(ci,/actions\/checkout@v7/);assert.match(ci,/actions\/setup-node@v7/);assert.match(ci,/node-version-file: \.node-version/);assert.match(ci,/npm ci --ignore-scripts/);assert.match(ci,/npm run check/);assert.match(ci,/npm test/);assert.match(ci,/npm audit --omit=dev --audit-level=high/);assert.doesNotMatch(ci,/ubuntu-latest|actions\/(?:checkout|setup-node)@v4/);});
test('smoke de producción es manual y posterior a CI correcta de main',()=>{const smoke=fs.readFileSync(path.join(root,'.github','workflows','production-smoke.yml'),'utf8');assert.match(smoke,/workflow_dispatch:/);assert.match(smoke,/workflow_run:/);assert.match(smoke,/workflows: \[CI\]/);assert.match(smoke,/workflow_run\.conclusion == 'success'/);assert.match(smoke,/workflow_run\.head_branch == 'main'/);assert.match(smoke,/EXPECTED_COMMIT_SHA/);assert.match(smoke,/cancel-in-progress: true/);assert.match(smoke,/permissions:\s+contents: read/);assert.match(smoke,/runs-on: ubuntu-24\.04/);assert.match(smoke,/actions\/checkout@v7/);assert.match(smoke,/actions\/setup-node@v7/);assert.match(smoke,/timeout-minutes: 5/);assert.match(smoke,/npm run smoke:production/);assert.doesNotMatch(smoke,/pull_request:|\n\s+push:|ubuntu-latest|actions\/(?:checkout|setup-node)@v4/);});

test('assets PWA usan tipos y revalidación correcta',()=>{const web=fs.readFileSync(path.join(root,'src/routes/web.cjs'),'utf8');for(const [route,type] of [['/manifest.webmanifest','application/manifest+json'],['/service-worker.js','text/javascript'],['/offline.html','text/html'],['/icon-192.png','image/png'],['/icon-512.png','image/png']]){assert.ok(web.includes(`'${route}'`),route);assert.ok(web.includes(type),type);}assert.ok(web.includes("if (route === '/manifest.webmanifest' || route === '/service-worker.js') reply.header('cache-control', 'no-cache');"));});
test('las navegaciones, incluida verificación, usan red y fallback offline sin cachear la respuesta',()=>{const sw=fs.readFileSync(path.join(root,'public/service-worker.js'),'utf8');const navigation=sw.indexOf("if (request.mode === 'navigate')"),authBypass=sw.indexOf("if (url.pathname.startsWith('/auth/')) return;");assert.ok(navigation>=0&&authBypass>navigation);const navigationHandler=sw.slice(navigation,authBypass);assert.match(navigationHandler,/event\.respondWith\(networkFirst\(request, null\)\)/);assert.doesNotMatch(navigationHandler,/cache\.put|caches\.open/);assert.doesNotMatch(sw,/['"]\/auth\/verify['"]/);assert.match(sw,/url\.pathname\.startsWith\('\/api\/'\)/);});
