'use strict';

const test = require('node:test'); const assert = require('node:assert/strict');
const { BBOX, MAX_NODES, MAX_SEGMENTS, OSM_API_ENDPOINT, OVERPASS_ENDPOINTS, USER_AGENT, accessibility, buildOverpassQuery, deterministicUuid, fetchOsmApiSnapshot, fetchOverpass, fetchOverpassSnapshot, isWalkable, mergeOverpassPayloads, nodePolicy, overpassTiles, parseOsmXml, parseOverpass, publishNetwork } = require('../scripts/import-osm-pilot.cjs');

const payload = { osm3s:{timestamp_osm_base:'2026-09-28T12:00:00Z'}, elements:[
  {type:'node',id:1,lat:37.39,lon:-5.99},{type:'node',id:2,lat:37.391,lon:-5.989},{type:'node',id:3,lat:37.392,lon:-5.988},
  {type:'way',id:10,nodes:[1,2,3],tags:{highway:'footway',name:'Paso de prueba',lit:'yes',wheelchair:'yes'}},
  {type:'way',id:11,nodes:[2,3],tags:{highway:'motorway'}}
] };

test('consulta Overpass está filtrada, acotada, optimizada e identificada',()=>{const query=buildOverpassQuery();for(const value of [BBOX.south,BBOX.west,BBOX.north,BBOX.east])assert.ok(query.includes(String(value)));assert.match(query,/timeout:90/);assert.match(query,/highway~.*footway.*steps/);assert.match(query,/out body qt/);assert.match(USER_AGENT,/RutaViva-Community/);assert.deepEqual([MAX_NODES,MAX_SEGMENTS],[15000,30000]);assert.deepEqual(OVERPASS_ENDPOINTS,['https://z.overpass-api.de/api/interpreter','https://lz4.overpass-api.de/api/interpreter','https://overpass.private.coffee/api/interpreter']);});
test('filtro excluye vías privadas/no peatonales',()=>{assert.equal(isWalkable({highway:'footway'}),true);assert.equal(isWalkable({highway:'footway',access:'private'}),false);assert.equal(isWalkable({highway:'motorway'}),false);});
test('políticas OSM interpretan barreras, superficies, pendientes y acceso',()=>{
  assert.deepEqual(nodePolicy({access:'private'}),{excluded:true,accessibilityStatus:'barrier'});
  assert.deepEqual(nodePolicy({barrier:'stile'}),{excluded:false,accessibilityStatus:'barrier'});
  assert.deepEqual(nodePolicy({barrier:'bollard',wheelchair:'yes'}),{excluded:false,accessibilityStatus:'compatible'});
  assert.deepEqual(nodePolicy({barrier:'gate',wheelchair:'no'}),{excluded:false,accessibilityStatus:'barrier'});
  assert.deepEqual(nodePolicy({kerb:'lowered'}),{excluded:false,accessibilityStatus:'compatible'});
  assert.equal(accessibility({surface:'cobblestone'}),'barrier');
  assert.equal(accessibility({incline:'9%'}),'barrier');
});
test('parser produce IDs deterministas, distancias reales y aristas dirigidas',()=>{const first=parseOverpass(payload),second=parseOverpass(payload);assert.equal(first.nodes.length,3);assert.equal(first.segments.length,4);assert.deepEqual(first,second);assert.equal(first.sourceDate,'2026-09-28');assert.equal(deterministicUuid('x'),deterministicUuid('x'));assert.match(first.nodes[0].id,/^[0-9a-f-]{36}$/);assert.ok(first.segments.every(segment=>segment.distanceMeters>100&&segment.distanceMeters<150));});
test('parser rechaza una instantánea sin fecha OSM verificable',()=>{assert.throws(()=>parseOverpass({elements:payload.elements}),/OSM_TIMESTAMP_INVALID/);});
test('parser XML conserva solo nodos y vías peatonales sin metadatos personales',()=>{const xml=`<osm><node id="1" lat="37.39" lon="-5.99" user="Persona"><tag k="barrier" v="gate"/></node><node id="2" lat="37.391" lon="-5.989"/><way id="10" user="Otra"><nd ref="1"/><nd ref="2"/><tag k="highway" v="footway"/><tag k="name" v="A &amp; B"/></way><way id="11"><nd ref="1"/><nd ref="2"/><tag k="highway" v="motorway"/></way><relation id="9" user="Oculta"/></osm>`;const elements=parseOsmXml(xml);assert.equal(elements.length,3);assert.deepEqual(elements[0],{type:'node',id:1,lat:37.39,lon:-5.99,tags:{barrier:'gate'}});assert.equal(elements[2].tags.name,'A & B');assert.equal(JSON.stringify(elements).includes('Persona'),false);assert.equal(JSON.stringify(elements).includes('user'),false);});
test('API OSM obtiene teselas y usa Date como fecha de instantánea',async()=>{const seen=[];const xml='<osm><node id="1" lat="37.39" lon="-5.99"/></osm>';const result=await fetchOsmApiSnapshot(async url=>{seen.push(url);return{ok:true,status:200,headers:{get:name=>name==='date'?'Wed, 30 Sep 2026 12:00:00 GMT':null},text:async()=>xml};},{now:()=>Date.parse('2026-09-30T13:00:00Z'),timeoutMs:100});assert.equal(seen.length,16);assert.ok(seen.every(url=>url.startsWith(OSM_API_ENDPOINT)));assert.equal(result.elements.length,1);assert.equal(result.osm3s.timestamp_osm_base,'2026-09-30T12:00:00.000Z');});
test('dieciséis teselas cubren el bbox y se fusionan sin duplicados',()=>{const tiles=overpassTiles();assert.equal(tiles.length,16);assert.equal(Math.min(...tiles.map(tile=>tile.south)),BBOX.south);assert.equal(Math.max(...tiles.map(tile=>tile.north)),BBOX.north);assert.equal(Math.min(...tiles.map(tile=>tile.west)),BBOX.west);assert.equal(Math.max(...tiles.map(tile=>tile.east)),BBOX.east);const now=Date.parse('2026-09-30T13:00:00Z');const merged=mergeOverpassPayloads([{osm3s:{timestamp_osm_base:'2026-09-30T12:00:00Z'},elements:[payload.elements[0],payload.elements[1]]},{osm3s:{timestamp_osm_base:'2026-09-30T12:05:00Z'},elements:[payload.elements[1],payload.elements[2]]}],{now:()=>now});assert.equal(merged.elements.length,3);assert.equal(merged.osm3s.timestamp_osm_base,'2026-09-30T12:00:00.000Z');});
test('fusión rechaza instantáneas antiguas o incoherentes',()=>{const current={osm3s:{timestamp_osm_base:'2026-09-30T12:00:00Z'},elements:[]};assert.throws(()=>mergeOverpassPayloads([current],{now:()=>Date.parse('2026-10-08T12:00:01Z')}),/OSM_SNAPSHOT_STALE/);assert.throws(()=>mergeOverpassPayloads([current,{osm3s:{timestamp_osm_base:'2026-09-29T12:00:00Z'},elements:[]}],{now:()=>Date.parse('2026-09-30T12:00:00Z')}),/OSM_SNAPSHOT_INCONSISTENT/);});
test('snapshot cambia de instancia solo si falla el conjunto completo',async()=>{const seen=[];const fresh='2026-09-30T12:00:00Z';const result=await fetchOverpassSnapshot(async endpoint=>{seen.push(endpoint);if(endpoint.includes('primary'))return{ok:false,status:400,headers:{get:()=>null}};return{ok:true,status:200,headers:{get:()=>null},json:async()=>({osm3s:{timestamp_osm_base:fresh},elements:[]})};},{endpoints:['https://primary.invalid','https://backup.invalid'],timeoutMs:100,now:()=>Date.parse('2026-09-30T13:00:00Z')});assert.equal(result.elements.length,0);assert.equal(seen.filter(value=>value.includes('primary')).length,1);assert.equal(seen.filter(value=>value.includes('backup')).length,16);});
test('snapshot subdivide automáticamente una tesela que devuelve 504',async()=>{let first=true;const progress=[];const fresh='2026-09-30T12:00:00Z';const result=await fetchOverpassSnapshot(async()=>{if(first){first=false;return{ok:false,status:504,headers:{get:()=>null}};}return{ok:true,status:200,headers:{get:()=>null},json:async()=>({osm3s:{timestamp_osm_base:fresh},elements:[]})};},{endpoints:['https://primary.invalid'],timeoutMs:100,now:()=>Date.parse('2026-09-30T13:00:00Z'),onProgress:value=>progress.push(value)});assert.equal(result.elements.length,0);assert.equal(progress.at(-1).tile,19);assert.equal(progress.at(-1).total,19);});
test('Overpass reintenta 429 respetando Retry-After y no reintenta otros 4xx',async()=>{
  const delays=[];const endpoints=[];let calls=0;
  const recovered=await fetchOverpass(async endpoint=>{endpoints.push(endpoint);calls+=1;return calls===1?{ok:false,status:429,headers:{get:()=> '2'}}:{ok:true,status:200,headers:{get:()=>null},json:async()=>payload};},{attempts:2,delay:async milliseconds=>delays.push(milliseconds),timeoutMs:100});
  assert.equal(recovered,payload);assert.equal(calls,2);assert.deepEqual(delays,[30000]);assert.deepEqual(endpoints,OVERPASS_ENDPOINTS.slice(0,2));
  calls=0;
  await assert.rejects(()=>fetchOverpass(async()=>{calls+=1;return{ok:false,status:400,headers:{get:()=>null}};},{attempts:3,delay:async()=>{},timeoutMs:100}),/OVERPASS_HTTP_400/);
  assert.equal(calls,1);
});
test('publicación es transaccional y rollback conserva release previo',async()=>{const calls=[];const client={query:async(text)=>{calls.push(String(text));if(String(text).startsWith('INSERT INTO app.route_segments'))throw new Error('synthetic');return{rows:[]};}};await assert.rejects(()=>publishNetwork(client,parseOverpass(payload),{releaseId:'30000000-0000-4000-8000-000000000001'}));assert.equal(calls[0],'BEGIN');assert.equal(calls.at(-1),'ROLLBACK');assert.equal(calls.some(call=>call.includes("status='retired'")),false);});
