'use strict';

const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const {pathToFileURL}=require('node:url');const test=require('node:test');const assert=require('node:assert/strict');
const {createApp}=require('../src/app.cjs');const {loadConfig}=require('../src/config.cjs');
const root=path.resolve(__dirname,'..');const config=loadConfig({NODE_ENV:'test'});const headers={host:config.allowedHost};

function extractFunction(source,name){const start=source.indexOf(`async function ${name}`);assert.notEqual(start,-1,`función ${name}`);const signatureEnd=source.indexOf('){',start);assert.notEqual(signatureEnd,-1,`firma ${name}`);const brace=signatureEnd+1;let depth=0;for(let index=brace;index<source.length;index+=1){if(source[index]==='{')depth+=1;else if(source[index]==='}'){depth-=1;if(depth===0)return source.slice(start,index+1);}}throw new Error(`No se pudo extraer ${name}`);}

test('portada, verificación y assets propios sirven CSP estricta para OSM',async()=>{const app=createApp({config,logger:false});try{for(const url of ['/','/auth/verify']){const response=await app.inject({method:'GET',url,headers});assert.equal(response.statusCode,200);assert.match(response.headers['content-security-policy'],/script-src 'self'/);assert.match(response.headers['content-security-policy'],/https:\/\/tile\.openstreetmap\.org/);assert.doesNotMatch(response.headers['content-security-policy'],/unsafe-inline/);assert.match(response.body,/Ruta orientativa/);assert.match(response.body,/<main id="contenido" tabindex="-1">/);assert.doesNotMatch(response.body,/<script[^>]*>\s*[^<]/);}for(const url of ['/styles.css','/app.js','/map.js','/contribution-recovery.mjs','/vendor/maplibre/maplibre-gl.mjs'])assert.equal((await app.inject({method:'GET',url,headers})).statusCode,200);}finally{await app.close();}});

test('frontend retira token, reintenta con identidad estable y protege mutaciones',()=>{const source=fs.readFileSync(path.join(root,'public/app.js'),'utf8');assert.ok(source.indexOf('history.replaceState')<source.indexOf('fetch('));assert.match(source,/let verificationToken=null/);assert.doesNotMatch(source,/localStorage|document\.cookie/);assert.match(source,/PENDING_CONTRIBUTION_KEY/);assert.match(source,/sessionStorage\.setItem\(PENDING_CONTRIBUTION_KEY,JSON\.stringify\(pendingContribution\)\)/);assert.match(source,/payloadFingerprint=await fingerprint/);assert.match(source,/pendingContribution=\{id:crypto\.randomUUID\(\),fingerprint:payloadFingerprint,version:null\}/);assert.doesNotMatch(source,/sessionStorage[^;]*(verificationToken|email|description|geometry)/i);assert.match(source,/recoveryDecision\(current\.status\)/);assert.match(source,/accessRequest=\{email,key:crypto\.randomUUID\(\)\}/);assert.match(source,/'idempotency-key':accessRequest\.key/);assert.match(source,/error\.code!=='CSRF_INVALID'\|\|attempt===1/);assert.match(source,/\/api\/v1\/auth\/csrf/);assert.match(source,/'x-csrf-token'/);assert.match(source,/El enlace no es válido o ha caducado/);assert.match(source,/cooldown=Date\.now\(\)\+30000/);});

test('mutación CSRF no declara JSON cuando la petición no tiene cuerpo',async()=>{const source=fs.readFileSync(path.join(root,'public/app.js'),'utf8');const calls=[];const context={navigator:{onLine:true},Error,JSON,api:async(path,options)=>{calls.push({path,options});return path==='/api/v1/auth/csrf'?{csrfToken:'csrf-demo'}:{ok:true};}};vm.runInNewContext(`${extractFunction(source,'csrfMutation')};globalThis.csrfMutation=csrfMutation;`,context);await context.csrfMutation('/api/v1/auth/logout','POST');assert.equal(calls.length,2);assert.deepEqual({...calls[1].options.headers},{'x-csrf-token':'csrf-demo'});assert.equal(calls[1].options.body,undefined);calls.length=0;await context.csrfMutation('/api/v1/example','POST',{value:1},{'idempotency-key':'idem-demo'});assert.deepEqual({...calls[1].options.headers},{'x-csrf-token':'csrf-demo','idempotency-key':'idem-demo','content-type':'application/json'});assert.equal(calls[1].options.body,'{"value":1}');});

test('logout bloquea dobles pulsaciones y separa el cierre del refresco secundario',async()=>{const source=fs.readFileSync(path.join(root,'public/app.js'),'utf8'),elements={logout:{disabled:false,textContent:'Cerrar sesión'},'account-section':{values:{},setAttribute(name,value){this.values[name]=value;}},'account-status':{textContent:''},'access-status':{textContent:''},'account-heading':{focused:false,focus(){this.focused=true;}}};let release,calls=0,authViews=0,refreshes=0;const pending=new Promise(resolve=>{release=resolve;});const context={Error,$:id=>elements[id],csrfMutation:async()=>{calls+=1;await pending;},setAuthView:()=>{authViews+=1;},loadContributions:async()=>{refreshes+=1;throw new Error('refresco secundario fallido');}};vm.runInNewContext(`let user={id:'demo'};let logoutInFlight=false;${extractFunction(source,'logout')};globalThis.logout=logout;globalThis.readUser=()=>user;`,context);const first=context.logout(),second=context.logout();assert.equal(calls,1);assert.equal(elements.logout.disabled,true);assert.equal(elements.logout.textContent,'Cerrando sesión…');assert.equal(elements['account-section'].values['aria-busy'],'true');assert.equal(elements['account-status'].textContent,'Cerrando la sesión en este navegador…');release();await Promise.all([first,second]);await new Promise(resolve=>setImmediate(resolve));assert.equal(context.readUser(),null);assert.equal(authViews,1);assert.doesNotMatch(elements['account-status'].textContent,/No se ha cerrado la sesión/);assert.equal(refreshes,1);assert.equal(elements['access-status'].textContent,'Sesión cerrada en este navegador. Las sesiones de otros dispositivos siguen abiertas.');assert.equal(elements['account-heading'].focused,true);assert.equal(elements.logout.disabled,false);assert.equal(elements.logout.textContent,'Cerrar sesión');assert.equal(elements['account-section'].values['aria-busy'],'false');});

test('logout conserva la cuenta y explica los errores sin fingir éxito',async()=>{const source=fs.readFileSync(path.join(root,'public/app.js'),'utf8');for(const [error,message] of [Object.assign(new Error('offline'),{code:'OFFLINE'}),new Error('server')].map((error,index)=>[error,index===0?'No se ha cerrado la sesión. Comprueba tu conexión y vuelve a intentarlo.':'No se ha cerrado la sesión. Inténtalo de nuevo.'])){const elements={logout:{disabled:false,textContent:'Cerrar sesión'},'account-section':{values:{},setAttribute(name,value){this.values[name]=value;}},'account-status':{textContent:''},'access-status':{textContent:''},'account-heading':{focus(){}}};let authViews=0,refreshes=0;const context={Error,$:id=>elements[id],csrfMutation:async()=>{throw error;},setAuthView:()=>{authViews+=1;},loadContributions:async()=>{refreshes+=1;}};vm.runInNewContext(`let user={id:'demo'};let logoutInFlight=false;${extractFunction(source,'logout')};globalThis.logout=logout;globalThis.readUser=()=>user;`,context);await context.logout();assert.equal(context.readUser().id,'demo');assert.equal(authViews,0);assert.equal(refreshes,0);assert.equal(elements['account-status'].textContent,message);assert.equal(elements.logout.disabled,false);assert.equal(elements['account-section'].values['aria-busy'],'false');}});

test('controles de dibujo invocan las implementaciones cargadas de forma diferida',()=>{const source=fs.readFileSync(path.join(root,'public/app.js'),'utf8');for(const [id,handler] of [['draw-center','addCenterPoint'],['draw-undo','undoPoint'],['draw-clear','clearDrawing']]){assert.match(source,new RegExp(`\\$\\('${id}'\\)\\.addEventListener\\('click',\\(\\)=>${handler}\\(\\)\\)`));assert.doesNotMatch(source,new RegExp(`\\$\\('${id}'\\)\\.addEventListener\\('click',${handler}\\)`));}});

test('recuperación clasifica terminales y solo limpia el pendiente coincidente',async()=>{const moduleUrl=pathToFileURL(path.join(root,'public/contribution-recovery.mjs')).href;const {pendingMatches,recoveryDecision}=await import(moduleUrl);const pending={id:'11111111-1111-4111-8111-111111111111'};assert.equal(pendingMatches(pending,pending.id),true);assert.equal(pendingMatches(pending,'22222222-2222-4222-8222-222222222222'),false);for(const status of ['submitted','under_review','published'])assert.equal(recoveryDecision(status),'complete');assert.equal(recoveryDecision('draft'),'retry');for(const status of ['withdrawn','rejected'])assert.equal(recoveryDecision(status),'discard');assert.equal(recoveryDecision('unexpected'),'unknown');const source=fs.readFileSync(path.join(root,'public/app.js'),'utf8');assert.match(source,/clearPendingContribution\(item\.id\)/);assert.match(source,/decision==='discard'/);});

test('mapa, lista y formulario conservan accesibilidad responsive',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),css=fs.readFileSync(path.join(root,'public/styles.css'),'utf8');assert.match(html,/aria-describedby="access-status local-note"/);assert.match(html,/aria-live="assertive"/);assert.match(html,/id="contributions-list"/);assert.match(html,/Datos equivalentes al gráfico/);assert.match(html,/Añadir punto en el centro/);assert.match(html,/© OpenStreetMap contributors/);assert.match(css,/min-width:320px/);assert.match(css,/@media\(max-width:360px\)/);assert.match(css,/:focus-visible/);assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/minmax\(0,1fr\)/);});

test('planificador A-B ofrece controles equivalentes y recorrido textual',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),app=fs.readFileSync(path.join(root,'public/app.js'),'utf8'),map=fs.readFileSync(path.join(root,'public/map.js'),'utf8');assert.match(html,/id="route-planner"/);assert.match(html,/<fieldset id="route-fieldset" aria-busy="false"><legend>Planifica una ruta con menos barreras conocidas<\/legend>/);assert.match(html,/data-route-map="origin"/);assert.match(html,/data-route-center="destination"/);assert.match(html,/id="route-progress"[^>]*role="status"/);assert.match(html,/id="route-status"[^>]*aria-live="polite"/);assert.match(html,/id="route-error"[^>]*role="alert"[^>]*tabindex="-1"/);assert.match(html,/id="route-retry"/);assert.match(html,/no garantiza seguridad ni accesibilidad/);assert.match(app,/Recorrido textual/);assert.match(app,/ROUTING_DATA_NOT_READY/);assert.match(app,/setRoutePlanPoints\(routePoints\.origin,routePoints\.destination\)/);assert.match(map,/planned-accessible/);assert.match(map,/line-dasharray/);});

test('la tabla de actividad adopta filas etiquetadas sin desbordar en móvil',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),css=fs.readFileSync(path.join(root,'public/styles.css'),'utf8');assert.match(html,/<table class="activity-table">/);assert.match(html,/<thead><tr><th>Día<\/th><th>Recibidas<\/th><th>Publicadas<\/th><th>Pendientes<\/th><\/tr><\/thead>/);assert.match(css,/@media\(max-width:560px\)/);assert.match(css,/\.activity-table\{display:block;width:100%;max-width:100%\}/);assert.match(css,/\.activity-table td\{[^}]*min-width:0;[^}]*overflow-wrap:anywhere/);for(const label of ['Día','Recibidas','Publicadas','Pendientes'])assert.ok(css.includes(`content:"${label}"`),label);assert.doesNotMatch(css,/\.activity-table thead\{[^}]*display:none/);assert.match(css,/\.activity-table thead\{[^}]*clip-path:inset\(50%\)/);});

test('la guía pública explica el uso esencial sin depender de JavaScript ni sesión',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),css=fs.readFileSync(path.join(root,'public/styles.css'),'utf8');assert.match(html,/<a href="#ayuda">Cómo usar<\/a>/);assert.match(html,/id="ayuda"/);assert.doesNotMatch(html,/<section id="ayuda"[^>]*\shidden(?:\s|>)/);assert.match(html,/Resumen rápido: cuatro pasos/);assert.ok((html.match(/<details>/g)||[]).length>=7);assert.match(html,/<dl class="help-glossary">/);for(const text of ['Ver en mapa','Ver historial','Tomar caso','comprueba los datos y el dibujo','escribe un motivo real','Publicar','Rechazar','Actualizar','Coincide','No coincide','Quitar respuesta','No puedes valorar tu propia aportación'])assert.ok(html.includes(text),text);assert.match(html,/Ningún moderador puede aprobar su propia aportación/);assert.match(html,/deben revisarse mutuamente/);assert.equal((html.match(/El enlace inicia sesión únicamente en el navegador y dispositivo donde lo abras\./g)||[]).length,2);assert.match(html,/Si lo abres en el móvil, la sesión quedará abierta en el móvil, no en este ordenador\. No compartas el enlace\./);assert.match(html,/id="account-heading" tabindex="-1"/);assert.match(html,/id="account-section" class="card" aria-busy="false" hidden/);assert.match(html,/id="account-status"[^>]*role="status"[^>]*aria-live="polite"/);assert.match(html,/Añadir punto en el centro/);assert.match(html,/Con teclado/);assert.match(html,/ruta orientativa/);assert.match(css,/\.help-topics summary\{min-height:44px/);assert.match(css,/font-size:1rem;line-height:1\.5/);assert.match(css,/\.help\{overflow-wrap:anywhere\}/);});

test('la guía detalla planificación, significado y ejemplo completo',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');for(const text of ['Calcular una ruta de A a B','Elegir en mapa','Usar centro','Intercambiar A y B','cobertura accesible','Puntuación','Ejemplo completo: informar de una barrera','no garantiza que la calle esté libre'])assert.ok(html.includes(text),text);assert.ok((html.match(/<details>/g)||[]).length>=9);});

test('PWA declara instalación accesible y fallback manual para móvil',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),manifest=JSON.parse(fs.readFileSync(path.join(root,'public/manifest.webmanifest'),'utf8'));assert.match(html,/<link rel="manifest" href="\/manifest\.webmanifest">/);assert.match(html,/<link rel="apple-touch-icon" href="\/icon-192\.png">/);assert.match(html,/id="install-app"[^>]*aria-describedby="pwa-status"/);assert.match(html,/id="pwa-status"[^>]*role="status"[^>]*aria-live="polite"/);assert.match(html,/id="connection-status"[^>]*role="status"[^>]*aria-live="polite"/);assert.match(html,/Android:[\s\S]*iPhone o iPad:[\s\S]*Safari/);assert.equal(manifest.display,'standalone');assert.deepEqual(manifest.icons.map(icon=>icon.sizes),['192x192','512x512']);const offline=fs.readFileSync(path.join(root,'public/offline.html'),'utf8');assert.match(offline,/RutaViva no pudo responder en este momento/);assert.match(offline,/conexión lenta o a una pausa temporal del servicio/);assert.match(offline,/Comprueba tu conexión y vuelve a intentarlo/);assert.match(offline,/no guarda ni envía cambios mientras estás sin conexión/);const app=fs.readFileSync(path.join(root,'public/app.js'),'utf8');assert.match(app,/navigator\.serviceWorker\.register\('\/service-worker\.js'/);assert.match(app,/if\(!navigator\.onLine\).*no se guardó ni envió la aportación/);assert.match(app,/if\(!navigator\.onLine\).*OFFLINE/);});

test('service worker solo contempla recursos estáticos locales y excluye API, auth y mapas externos',()=>{const sw=fs.readFileSync(path.join(root,'public/service-worker.js'),'utf8');assert.match(sw,/url\.origin !== self\.location\.origin/);assert.match(sw,/url\.pathname\.startsWith\('\/api\/'\)/);assert.match(sw,/url\.pathname\.startsWith\('\/auth\/'\)/);assert.match(sw,/const CACHEABLE_PATHS = new Set\(SHELL_ASSETS\)/);assert.match(sw,/key\.startsWith\(CACHE_PREFIX\).*key !== CACHE_NAME/);assert.doesNotMatch(sw,/addEventListener\(['"]sync['"]\)|tile\.openstreetmap|localStorage|sessionStorage|indexedDB/i);});

test('service worker actualiza en red antes de usar la allowlist cacheada sin forzar clientes antiguos',()=>{const sw=fs.readFileSync(path.join(root,'public/service-worker.js'),'utf8');assert.match(sw,/CACHE_NAME = 'rutaviva-shell-v2'/);assert.match(sw,/const response = await fetch\(request, \{ signal: controller\.signal \}\)/);assert.match(sw,/setTimeout\(\(\) => controller\.abort\(\), NETWORK_TIMEOUT_MS\)/);assert.match(sw,/if \(!response\.ok\) return response/);assert.match(sw,/cache\.put\(cacheKey, response\.clone\(\)\)/);assert.match(sw,/const fallback = await caches\.match\(cacheKey \|\| '\/offline\.html'\);\r?\n    return fallback \|\| Response\.error\(\);/);assert.doesNotMatch(sw,/skipWaiting|clients\.claim/);});

test('networkFirst conserva HTTP 404 y usa offline solo si falla fetch',async()=>{const source=fs.readFileSync(path.join(root,'public/service-worker.js'),'utf8');async function run(fetchImpl){const lookups=[],offline=new Response('sin conexión',{status:200});let writes=0;const context={self:{addEventListener(){}},caches:{match:async key=>{lookups.push(key);return key==='/offline.html'?offline:null;},open:async()=>({put:async()=>{writes+=1;}})},fetch:fetchImpl,AbortController,setTimeout,clearTimeout,Response};vm.runInNewContext(source,context);return{result:await context.networkFirst(new Request('https://rutaviva.example/app.js'),null),lookups,writes};}const notFound=new Response('no encontrado',{status:404});const http=await run(async()=>notFound);assert.strictEqual(http.result,notFound);assert.deepEqual(http.lookups,[]);assert.equal(http.writes,0);const failed=await run(async()=>{throw new Error('offline');});assert.equal(await failed.result.text(),'sin conexión');assert.deepEqual(failed.lookups,['/offline.html']);assert.equal(failed.writes,0);});

test('portada de credibilidad usa datos reales, supresión y estados honestos',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),app=fs.readFileSync(path.join(root,'public/app.js'),'utf8'),css=fs.readFileSync(path.join(root,'public/styles.css'),'utf8');for(const id of ['confianza','trust-publicados','trust-tasa','zonas','zone-cards','metodologia','pulse-7','pulse-30'])assert.match(html,new RegExp(`id="${id}"`));assert.match(html,/tasa de publicación tras moderación/);assert.match(html,/menos de cinco participantes/);assert.match(app,/publicationRate/);assert.match(app,/privacySuppressed/);assert.doesNotMatch(app,/verificationRate/);assert.match(app,/\/api\/v1\/zones\/leaderboard/);assert.match(app,/\/api\/v1\/methodology/);assert.match(css,/\.trust-grid/);assert.match(css,/\.feature-steps/);});

test('bootstrap publica mapa y desactiva cuentas sin entrega real',async()=>{const database={query:async text=>String(text).includes('COUNT(zone.id)')?{rows:[{id:'10000000-0000-4000-8000-000000000001',slug:'sevilla',name:'Sevilla',countryCode:'ES',isApproximate:true,latitude:37.3,longitude:-5.9,zoneCount:0}]}:{rows:[]}};const app=createApp({config,database,authService:null,logger:false});try{const body=(await app.inject({method:'GET',url:'/api/v1/bootstrap',headers})).json();assert.equal(body.capabilities.accounts,false);assert.equal(body.capabilities.contributions,true);assert.equal(body.map.tileUrl,'https://tile.openstreetmap.org/{z}/{x}/{y}.png');}finally{await app.close();}});


test('bootstrap mantiene visible el aviso del enlace mágico en el dominio público',async()=>{
  const source=fs.readFileSync(path.join(root,'public/app.js'),'utf8');
  const elements={'access-form':{hidden:true},'local-note':{hidden:false},'contribution-zone':{replaceChildren(){}},'route-status':{textContent:''},'map-status':{textContent:''}};
  const context={location:{hostname:'rutaviva-community-sevilla-jv31.onrender.com'},$:id=>elements[id],Option:function(text,value){this.text=text;this.value=value;},api:async url=>url==='/api/v1/bootstrap'?{capabilities:{accounts:true,routes:false}}:{data:[]}};
  vm.runInNewContext(`let bootstrap,zones;${extractFunction(source,'loadBootstrap')};globalThis.loadBootstrap=loadBootstrap;`,context);
  await context.loadBootstrap();
  assert.equal(elements['access-form'].hidden,false);
  assert.equal(elements['local-note'].hidden,false);
});

test('edición y reportes tienen controles visibles, estados accesibles e idempotencia estable',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),app=fs.readFileSync(path.join(root,'public/app.js'),'utf8'),map=fs.readFileSync(path.join(root,'public/map.js'),'utf8'),css=fs.readFileSync(path.join(root,'public/styles.css'),'utf8');for(const id of ['contribution-cancel','report-dialog','report-form','report-status','reports-status','reports-list'])assert.match(html,new RegExp(`id="${id}"`));assert.match(app,/Editar borrador/);assert.match(app,/Guardar cambios/);assert.match(app,/item\.kind!=='shortcut'/);assert.match(app,/setDrawingGeometry\(item\.geometry\)/);assert.match(app,/Hay cambios sin guardar/);assert.match(app,/No se pudieron guardar los cambios\. Los datos escritos se conservan/);assert.match(app,/Reportar contenido/);assert.match(app,/reportRequestId=crypto\.randomUUID\(\)/);assert.match(app,/'idempotency-key':reportRequestId/);assert.match(app,/reportDecisionRequests/);assert.match(app,/no se ha retirado automáticamente/);assert.match(app,/Confirmar y retirar/);assert.match(map,/export function setDrawingGeometry/);assert.doesNotMatch(app,/function openReport[\s\S]{0,1200}window\.prompt/);assert.match(css,/dialog\{width:min\(36rem,calc\(100% - 1rem\)\)/);assert.match(css,/\.form-actions button\{min-width:44px\}/);});

test('guardar un borrador conserva el éxito aunque falle el refresco posterior',async()=>{const source=fs.readFileSync(path.join(root,'public/app.js'),'utf8');const elements={'contribution-status':{textContent:'',focus(){this.focused=true;}},'contribution-measurement':{value:'unmeasured'},'contribution-width':{value:'',focus(){}},'contribution-zone':{value:''},'contribution-title':{value:'Paso estrecho revisado'},'contribution-description':{value:'Descripción'},'contribution-condition':{value:'narrow_passage'},'contribution-observed':{value:'2026-10-06'},'contribution-permanence':{value:'unknown'},'personal-data-confirmed':{checked:true},'contribution-submit':{disabled:false},'contribution-cancel':{disabled:false},'contribute-title':{focus(){this.focused=true;}}};const form={reportValidity:()=>true,values:{},setAttribute(name,value){this.values[name]=value;}};let writes=0,cancellations=0;const context={Error,Number,navigator:{onLine:true},document:{querySelectorAll:()=>[]},$:id=>elements[id],syncContributionKind:()=> 'barrier',geometryFor:()=>({type:'Point',coordinates:[-5.9,37.3]}),csrfMutation:async()=>{writes+=1;},cancelEdit:()=>{cancellations+=1;},loadContributions:async()=>{throw new Error('refresco fallido');},submitContribution:async()=>{throw new Error('no esperado');}};vm.runInNewContext(`let editingContribution={id:'11111111-1111-4111-8111-111111111111',version:2,geometry:{type:'Point',coordinates:[-5.9,37.3]}};let contributionMutation=false;${extractFunction(source,'submitContributionV39')};globalThis.submitContributionV39=submitContributionV39;`,context);await context.submitContributionV39({currentTarget:form,preventDefault(){}});assert.equal(writes,1);assert.equal(cancellations,1);assert.match(elements['contribution-status'].textContent,/^Borrador actualizado/);assert.doesNotMatch(elements['contribution-status'].textContent,/No se pudieron guardar los cambios/);assert.equal(elements['contribution-submit'].disabled,false);assert.equal(elements['contribution-cancel'].disabled,false);assert.equal(form.values['aria-busy'],'false');});

test('una decisión de reporte confirmada no se convierte en falso error por el refresco',async()=>{const source=fs.readFileSync(path.join(root,'public/app.js'),'utf8');const elements={'reports-status':{textContent:''}};const buttons=[{disabled:false},{disabled:false}];const card={busy:'false',getAttribute(){return this.busy;},setAttribute(name,value){if(name==='aria-busy')this.busy=value;},querySelectorAll:()=>buttons};let decisions=0;const context={Map,Promise,crypto:{randomUUID:()=> '22222222-2222-4222-8222-222222222222'},$:id=>elements[id],csrfMutation:async()=>{decisions+=1;},loadReports:async()=>{throw new Error('refresco fallido');},loadContributions:async()=>{},loadActivity:async()=>{}};vm.runInNewContext(`const reportDecisionRequests=new Map();${extractFunction(source,'decideReport')};globalThis.decideReport=decideReport;globalThis.pending=reportDecisionRequests;`,context);await context.decideReport({id:'33333333-3333-4333-8333-333333333333',version:1},'resolve','Riesgo confirmado',card);assert.equal(decisions,1);assert.match(elements['reports-status'].textContent,/^Reporte confirmado\. La aportación se retiró/);assert.match(elements['reports-status'].textContent,/No se pudo actualizar toda la vista/);assert.doesNotMatch(elements['reports-status'].textContent,/No se pudo registrar la decisión/);assert.equal(context.pending.size,0);assert.equal(card.busy,'true');assert.ok(buttons.every(button=>button.disabled));});

test('Escape no cierra el diálogo mientras se envía un reporte',()=>{const source=fs.readFileSync(path.join(root,'public/app.js'),'utf8');assert.match(source,/function cancelReportDialog\(event\)\{if\(reportMutation\)\{event\.preventDefault\(\);return;\}/);assert.match(source,/\$\('report-dialog'\)\.addEventListener\('cancel',cancelReportDialog\)/);});
