'use strict';

const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');const test=require('node:test');const assert=require('node:assert/strict');
const {createApp}=require('../src/app.cjs');const {loadConfig}=require('../src/config.cjs');
const root=path.resolve(__dirname,'..');const config=loadConfig({NODE_ENV:'test'});const headers={host:config.allowedHost};

test('portada, verificación y assets propios sirven CSP estricta para OSM',async()=>{const app=createApp({config,logger:false});try{for(const url of ['/','/auth/verify']){const response=await app.inject({method:'GET',url,headers});assert.equal(response.statusCode,200);assert.match(response.headers['content-security-policy'],/script-src 'self'/);assert.match(response.headers['content-security-policy'],/https:\/\/tile\.openstreetmap\.org/);assert.doesNotMatch(response.headers['content-security-policy'],/unsafe-inline/);assert.match(response.body,/Ruta orientativa/);assert.match(response.body,/<main id="contenido" tabindex="-1">/);assert.doesNotMatch(response.body,/<script[^>]*>\s*[^<]/);}for(const url of ['/styles.css','/app.js','/map.js','/contribution-recovery.mjs','/vendor/maplibre/maplibre-gl.mjs'])assert.equal((await app.inject({method:'GET',url,headers})).statusCode,200);}finally{await app.close();}});

test('frontend retira token, reintenta con identidad estable y protege mutaciones',()=>{const source=fs.readFileSync(path.join(root,'public/app.js'),'utf8');assert.ok(source.indexOf('history.replaceState')<source.indexOf('fetch('));assert.match(source,/let verificationToken=null/);assert.doesNotMatch(source,/localStorage|document\.cookie/);assert.match(source,/PENDING_CONTRIBUTION_KEY/);assert.match(source,/sessionStorage\.setItem\(PENDING_CONTRIBUTION_KEY,JSON\.stringify\(pendingContribution\)\)/);assert.match(source,/payloadFingerprint=await fingerprint/);assert.match(source,/pendingContribution=\{id:crypto\.randomUUID\(\),fingerprint:payloadFingerprint,version:null\}/);assert.doesNotMatch(source,/sessionStorage[^;]*(verificationToken|email|description|geometry)/i);assert.match(source,/recoveryDecision\(current\.status\)/);assert.match(source,/accessRequest=\{email,key:crypto\.randomUUID\(\)\}/);assert.match(source,/'idempotency-key':accessRequest\.key/);assert.match(source,/error\.code!=='CSRF_INVALID'\|\|attempt===1/);assert.match(source,/\/api\/v1\/auth\/csrf/);assert.match(source,/'x-csrf-token'/);assert.match(source,/El enlace no es válido o ha caducado/);assert.match(source,/cooldown=Date\.now\(\)\+30000/);assert.match(source,/location\.hostname/);});

test('recuperación clasifica terminales y solo limpia el pendiente coincidente',async()=>{const moduleUrl=pathToFileURL(path.join(root,'public/contribution-recovery.mjs')).href;const {pendingMatches,recoveryDecision}=await import(moduleUrl);const pending={id:'11111111-1111-4111-8111-111111111111'};assert.equal(pendingMatches(pending,pending.id),true);assert.equal(pendingMatches(pending,'22222222-2222-4222-8222-222222222222'),false);for(const status of ['submitted','under_review','published'])assert.equal(recoveryDecision(status),'complete');assert.equal(recoveryDecision('draft'),'retry');for(const status of ['withdrawn','rejected'])assert.equal(recoveryDecision(status),'discard');assert.equal(recoveryDecision('unexpected'),'unknown');const source=fs.readFileSync(path.join(root,'public/app.js'),'utf8');assert.match(source,/clearPendingContribution\(item\.id\)/);assert.match(source,/decision==='discard'/);});

test('mapa, lista y formulario conservan accesibilidad responsive',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),css=fs.readFileSync(path.join(root,'public/styles.css'),'utf8');assert.match(html,/aria-describedby="access-status local-note"/);assert.match(html,/aria-live="assertive"/);assert.match(html,/id="contributions-list"/);assert.match(html,/Datos equivalentes al gráfico/);assert.match(html,/Añadir punto en el centro/);assert.match(html,/© OpenStreetMap contributors/);assert.match(css,/min-width:320px/);assert.match(css,/@media\(max-width:360px\)/);assert.match(css,/:focus-visible/);assert.match(css,/prefers-reduced-motion:reduce/);assert.match(css,/minmax\(0,1fr\)/);});

test('la tabla de actividad adopta filas etiquetadas sin desbordar en móvil',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),css=fs.readFileSync(path.join(root,'public/styles.css'),'utf8');assert.match(html,/<table class="activity-table">/);assert.match(html,/<thead><tr><th>Día<\/th><th>Recibidas<\/th><th>Publicadas<\/th><th>Pendientes<\/th><\/tr><\/thead>/);assert.match(css,/@media\(max-width:560px\)/);assert.match(css,/\.activity-table\{display:block;width:100%;max-width:100%\}/);assert.match(css,/\.activity-table td\{[^}]*min-width:0;[^}]*overflow-wrap:anywhere/);for(const label of ['Día','Recibidas','Publicadas','Pendientes'])assert.ok(css.includes(`content:"${label}"`),label);assert.doesNotMatch(css,/\.activity-table thead\{[^}]*display:none/);assert.match(css,/\.activity-table thead\{[^}]*clip-path:inset\(50%\)/);});

test('la guía pública explica el uso esencial sin depender de JavaScript ni sesión',()=>{const html=fs.readFileSync(path.join(root,'public/index.html'),'utf8'),css=fs.readFileSync(path.join(root,'public/styles.css'),'utf8');assert.match(html,/<a href="#ayuda">Cómo usar<\/a>/);assert.match(html,/id="ayuda"/);assert.doesNotMatch(html,/<section id="ayuda"[^>]*\shidden(?:\s|>)/);assert.match(html,/Resumen rápido: cuatro pasos/);assert.ok((html.match(/<details>/g)||[]).length>=7);assert.match(html,/<dl class="help-glossary">/);for(const text of ['Ver en mapa','Ver historial','Tomar caso','comprueba los datos y el dibujo','escribe un motivo real','Publicar','Rechazar','Actualizar','Coincide','No coincide','Quitar respuesta','No puedes valorar tu propia aportación'])assert.ok(html.includes(text),text);assert.match(html,/Ningún moderador puede aprobar su propia aportación/);assert.match(html,/deben revisarse mutuamente/);assert.match(html,/No compartas ese enlace/);assert.match(html,/Añadir punto en el centro/);assert.match(html,/Con teclado/);assert.match(html,/ruta orientativa/);assert.match(css,/\.help-topics summary\{min-height:44px/);assert.match(css,/font-size:1rem;line-height:1\.5/);assert.match(css,/\.help\{overflow-wrap:anywhere\}/);});

test('bootstrap publica mapa y desactiva cuentas sin entrega real',async()=>{const database={query:async text=>String(text).includes('COUNT(zone.id)')?{rows:[{id:'10000000-0000-4000-8000-000000000001',slug:'sevilla',name:'Sevilla',countryCode:'ES',isApproximate:true,latitude:37.3,longitude:-5.9,zoneCount:0}]}:{rows:[]}};const app=createApp({config,database,authService:null,logger:false});try{const body=(await app.inject({method:'GET',url:'/api/v1/bootstrap',headers})).json();assert.equal(body.capabilities.accounts,false);assert.equal(body.capabilities.contributions,true);assert.equal(body.map.tileUrl,'https://tile.openstreetmap.org/{z}/{x}/{y}.png');}finally{await app.close();}});
